#This is workflow name
name: Hello

on: 
  workflow_dispatch:    

#These are the jobs
jobs:
# this is the name of the job
  greet:
  #This is githun runner 
    runs-on: ubuntu-latest     # instead of ubuntu we can also use mac,windows
    steps:
       - name: say hello to users
         run: echo "Hello user"

       - name: say hello to username
         run: echo "hello $USER"

  details:
      runs-on: ubuntu-latest
      steps:
        - name: show what is the version of python,docker ,etc
          run: docker --version && python --version
  
