# packages - issues ya vulnerabilities
#pip-audit
name: Dependency scan

on:
  workflow_call:

jobs:
    dependency-check:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            
            - name: setup python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: install pip audit
              run: |
                python -m pip install --upgrade pip
                pip install pip-audit

            - name: audit dependencies
              run: pip-audit -r requirements.txt 