# this will deploy the safe / secure / tested app to production
name: deploy to server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: SSH to production server                  #SSh and create devops where app run
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY}}
                script: |
                  echo "installing packages i.e., docker docker-compose"
                  sudo apt-get update && sudo apt-get install -y docker.io docker-compose
                  sudo usermod -aG docker $USER && newgrp docker
                  mkdir -p ~/devops
            
            - name: copy docker-compose file
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY}}
                source: docker-compose.yml
                target: ~/devops
                 
            - name: SSH to production server                 #ssh to prod server and run app
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY}}
                script: |
                  echo "running app"
                  export DOCKERHUB_USER=${{ secrets.DOCKERHUB_USER}}
                  export DOCKER_TAG=${{ github..sha}}
                  echo ${{ secrets.DOCKERHUB_TOKEN}} | docker login -u ${{ secrets.DOCKERHUB_USER}} --password-stdin
                  docker compose down && docker compose up -d --build --force-recreate --pull always
