name: Deploy flask app

on:
    workflow_dispatch:


jobs:
    
    delpoy:
        env:
         DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER}}
         DOCKER_TAG: ${{ github.sha}}
        runs-on: self-hosted


        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: set up docker compose
              uses: docker/setup-compose-action@v2

            - name: deploy with docker compose
              run: docker compose down && docker compose up -d --build --force-recreate --pull always

            