# this will deploy the safe / secure / tested app to production
name: deploy to server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH to production server
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY}}
                script: |
                  echo "starting deployment"
                 