name: DevSecOps end to end pipeline

on: 
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml 
        
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
    
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml 
    
    docker-lint:
        uses: ./.github/workflows/docker-lint.yml
   #  build only after all the code got scanned
    docker-build-push:
        needs: [code-quality,secrets-scan,dependency-scan,docker-lint]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit                                       # uses secrets from docker-build-push

    trivy:
        needs: [docker-build-push]
        uses: ./.github/workflows/image-scan.yml
    

