name: DevSecOps end to end pipeline

on: 
    workflow_dispatch:

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml 
        
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
    
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml 
    
    docker-lint:
        uses: ./.github/workflows/docker-lint.yml

    

