# scan the dockerfile for issues and common vulnerabilities and exposure
name: Docker lint

on:
    workflow_call:
    
jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: validate dockerfile
              uses: hadolint/hadolint-action@v3
              with:
                dockerfile: Dockerfile