# API keys , sensitive data , credentials\
#git leaks
name: secrets scan

on:
    workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0       #check all commits

            - name: Git leaks scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  #github actions manages it
